### ISSUE TITLE
Wont install

### ISSUE THREAD

**Issue by TomHarkness** [nitsky/homebrew-stm32#11]
Hey I'm trying to install this on High Sierra - brew is up to date. it fails on unzip.

tomharkness@ThMini:/usr/local/Homebrew$ brew install --verbose --debug arm-none-eabi-gcc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb
==> Installing arm-none-eabi-gcc from nitsky/stm32
/usr/bin/sandbox-exec -f /private/tmp/homebrew20180711-20313-p3akim.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew:/usr/local/Homebrew/Library/Homebrew/cask/lib -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb
==> Downloading https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2?revision=982ef8a4-1815-4651-9c44-6144c9d8b34b?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Mac%20OS%20X,7-2018-q2-update
Already downloaded: /Users/tomharkness/Library/Caches/Homebrew/arm-none-eabi-gcc-20180627.bz2
==> Verifying arm-none-eabi-gcc-20180627.bz2 checksum
bunzip2 -q /private/tmp/arm-none-eabi-gcc-20180711-20315-63u4dr/arm-none-eabi-gcc-20180627.bz2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Errno::ENOENT: No such file or directory - arm-none-eabi-gcc-20180627/arm-none-eabi

**Comment by TomHarkness** [comment]
I can fix this manually if during the install / unzip process I've already got the bz2 file up-zipped and renamed to "arm-none-eabi-gcc-20180627" and placed in the /private/tmp/.. folder that's created on install.

**Comment by nitsky** [comment]
Hi Tom, I merged a PR yesterday which probably broke this. I'm investigating now.

**Comment by TomHarkness** [comment]
Thanks mate. I've found a workaround for now ^ :)

**Comment by TomHarkness** [comment]
Hi, This still has not been resolved. Any chance of a fix soon ?

**Comment by jakobbak** [comment]
Hello Nitsky

I am having the exact same problem as TomHarkness. Wasn't able to fix a manual workaround though.
Would be very interested in hearing if this is fixable :)

Jupiter-8:~ jakob$ brew install --verbose --debug arm-none-eabi-gcc
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb
==> Installing arm-none-eabi-gcc from nitsky/stm32
/usr/bin/sandbox-exec -f /private/tmp/homebrew20180813-7133-1mcd2ma.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin17:/Library/Ruby/Site/2.3.0/universal-darwin17:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17:/usr/local/Homebrew/Library/Homebrew/cask/lib:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb
==> Downloading https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2?revision=982ef8a4-1815-4651-9c44-6144c9d8b34b?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Mac%20OS%20X,7-2018-q2-update
==> Downloading from https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1 (Macintosh; Intel Mac OS X 10.13.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/jakob/Library/Caches/Homebrew/arm-none-eabi-gcc-20180627.bz2.incomplete https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.6M  100 99.6M    0     0  4872k      0  0:00:20  0:00:20 --:--:-- 3494k
==> Verifying arm-none-eabi-gcc-20180627.bz2 checksum
tar xf /Users/jakob/Library/Caches/Homebrew/arm-none-eabi-gcc-20180627.bz2 -C /private/tmp/d20180813-7135-mmgaxl
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Errno::ENOENT: No such file or directory - arm-none-eabi-gcc-20180627/arm-none-eabi
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:

**Comment by nitsky** [comment]
This is fixable, I will resolve it ASAP. Thanks for the extra info.

**Comment by jakobbak** [comment]
Thanks Nitsky
Let me know when a possible fix is up and I'll give it another spin.

**Comment by tuffstudio** [comment]
Hey Nitsky,

I'm having same problem, manual workaround doesn't work.
All I'm getting is: 
Error: No such file or directory - arm-none-eabi-gcc-20180627/arm-none-eabi 

Any fix on the horizon?

**Comment by tuffstudio** [comment]
Dirty solution:

1. brew tap nitsky/stm32
2.edit 'arm-none-eabi-gcc.rb' in 'usr/local/Homebrew/Library/Taps/nitsky/homebrew-stm32/'
undo last commit: https://github.com/nitsky/homebrew-stm32/commit/5f5c118f63f4f0885debe2c92facc2084c600216

so "def install" is like this:

  def install
    puts Dir.pwd
    puts Dir["*"].join(", ")
    prefix.install "arm-none-eabi", "bin", "lib", "share"
  end 

3.brew install arm-none-eabi-gcc
4.brew install stlink

**Comment by nitsky** [comment]
@tuffstudio @jakobbak @TomHarkness I have updated the formula, please reopen the issue if you still run into trouble. Sorry for the long delay in getting this fixed.
