### ISSUE TITLE
Error: undefined method `desc' for ArmNoneEabiGcc:Class

### ISSUE THREAD

**Issue by bdunlay** [nitsky/homebrew-stm32#9]
Tried to follow your guide on http://davidyamnitsky.com/blog/2013/11/14/stm32-mac/ but hit this issue. Commenting out the `desc` line seems to do the trick. Would submit a patch, but I have absolutely zero ruby experience so I don't really know what I'm doing 😉 

More details: 

* OS X 10.10.5
* ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
* Homebrew 0.9.5

```
$ brew install arm-none-eabi-gcc
Error: undefined method `desc' for ArmNoneEabiGcc:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb:2:in `<class:ArmNoneEabiGcc>'
/usr/local/Library/Taps/nitsky/homebrew-stm32/arm-none-eabi-gcc.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

**Comment by nitsky** [comment]
Hi Brian, thank you for the report! I tested on my machine with OS X 10.11, Homebrew 0.9.9, ruby 2.3.0p0, and I was unable to reproduce the issue. Perhaps the older version of Homebrew doesn't support the `desc` line? Were you able to successfully follow the tutorial?

**Comment by bdunlay** [comment]
I [suspect](https://github.com/Homebrew/legacy-homebrew/pull/39911) you're right!

I was able to follow the tutorial and am happily building away. Thanks for your work, appreciate it!
